version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    background = 'transparent'
    foreground = '#6897BB'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = '#B57EDC'
    template = '{{ .Path }}'
    [blocks.segments.properties]
      style = 'full'
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#CC7832'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <#6897BB>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#FFC66D'
    background = 'transparent'
    template = '{{ .FormattedMs }}'
    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}#FF6B68{{end}}",
      "{{if eq .Code 0}}#6897BB{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}#FF6B68{{end}}",
    "{{if eq .Code 0}}#6897BB{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = '#6897BB'
  background = 'transparent'
  template = '❯❯ '
