import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMonoML Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoML Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoML Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoML Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
